version: 0.2
phases:
  install:
    runtime-versions:
      dotnet: 7.0
  pre_build:
    commands:
      - dotnet restore AWSCodePipelineDemo.csproj
  build:
    commands:
      - dotnet build AWSCodePipelineDemo.csproj
  post_build:
    commands:
      - dotnet publish -c Release -o ./app/ AWSCodePipelineDemo.csproj
artifacts:
  files:
    - '**/*'
